name: Python code practices
on: [push]
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install dependancy
        run : |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Push Repo
        run: |
          git config user.name sushil
          git config user.email contactsushil7@gmail.com
          git add .
          git commit -m"Addign actions"
          git push
      
        
